//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameRes.Formats.Strings {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class arcStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal arcStrings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameRes.Formats.Strings.arcStrings", typeof(arcStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Archive contents might be encrypted,
        ///choose appropriate encryption scheme. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AGSMightBeEncrypted {
            get {
                return ResourceManager.GetString("AGSMightBeEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Base archive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AMIBaseArchive {
            get {
                return ResourceManager.GetString("AMIBaseArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New archive will also contain entries from the base archive. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AMIBaseTooltip {
            get {
                return ResourceManager.GetString("AMIBaseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select base archive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AMIChooseBase {
            get {
                return ResourceManager.GetString("AMIChooseBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Amaterasu Translations Muv-Luv archive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AMIDescription {
            get {
                return ResourceManager.GetString("AMIDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No files suitable for AMI archive found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AMINoFiles {
            get {
                return ResourceManager.GetString("AMINoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArcDefault {
            get {
                return ResourceManager.GetString("ArcDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Archive content is encrypted.
        ///Choose appropriate encryption scheme. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArcEncryptedNotice {
            get {
                return ResourceManager.GetString("ArcEncryptedNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   32-bit hex number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArcHex32Bit {
            get {
                return ResourceManager.GetString("ArcHex32Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ignore encryption に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArcIgnoreEncryption {
            get {
                return ResourceManager.GetString("ArcIgnoreEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image is encrypted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArcImageEncrypted {
            get {
                return ResourceManager.GetString("ArcImageEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   no encryption に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArcNoEncryption {
            get {
                return ResourceManager.GetString("ArcNoEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArcReset {
            get {
                return ResourceManager.GetString("ArcReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose title or enter a password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArcTitleOrPassword {
            get {
                return ResourceManager.GetString("ArcTitleOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default file names encoding に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultEncoding {
            get {
                return ResourceManager.GetString("DefaultEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encryption keys に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DPKKeys {
            get {
                return ResourceManager.GetString("DPKKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Archive contains encrypted scripts.
        ///Choose encryption scheme or enter a passphrase. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FJSYSNotice {
            get {
                return ResourceManager.GetString("FJSYSNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose title or enter a key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GALChoose {
            get {
                return ResourceManager.GetString("GALChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   âge proprietary image format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GRPDescription {
            get {
                return ResourceManager.GetString("GRPDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Liar-soft proprietary script format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GSCDescription {
            get {
                return ResourceManager.GetString("GSCDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image is encrypted.
        ///Choose appropriate encryption scheme. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GYUImageEncrypted {
            get {
                return ResourceManager.GetString("GYUImageEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose game executable file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string INTChooseExe {
            get {
                return ResourceManager.GetString("INTChooseExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encrypted archives creation is not implemented. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string INTCreationNotice {
            get {
                return ResourceManager.GetString("INTCreationNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CatSystem2 engine resource archive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string INTDescription {
            get {
                return ResourceManager.GetString("INTDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check EXE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string INTExeButton {
            get {
                return ResourceManager.GetString("INTExeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Executable Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string INTExeFiles {
            get {
                return ResourceManager.GetString("INTExeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key not found within {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string INTKeyNotFound {
            get {
                return ResourceManager.GetString("INTKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Numeric key should be a 32-bit hexadecimal integer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string INTKeyRequirement {
            get {
                return ResourceManager.GetString("INTKeyRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Numeric key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string INTLabelNumericKey {
            get {
                return ResourceManager.GetString("INTLabelNumericKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Press &quot;Check EXE&quot; button to look for key within game executable file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string INTMessage1 {
            get {
                return ResourceManager.GetString("INTMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alternatively, enter archive encryption key or choose one of the predefined encryption schemes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string INTMessage2 {
            get {
                return ResourceManager.GetString("INTMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Archive directory is encrypted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string INTNotice {
            get {
                return ResourceManager.GetString("INTNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KCAPDefault {
            get {
                return ResourceManager.GetString("KCAPDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kogado game engine resource archive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KogadoDescription {
            get {
                return ResourceManager.GetString("KogadoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encryption scheme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelEncScheme {
            get {
                return ResourceManager.GetString("LabelEncScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Passphrase に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelPassphrase {
            get {
                return ResourceManager.GetString("LabelPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scheme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelScheme {
            get {
                return ResourceManager.GetString("LabelScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Liar-soft image archive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LWGDescription {
            get {
                return ResourceManager.GetString("LWGDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Archive contains encrypted scripts.
        ///Choose encryption scheme or enter a passphrase. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MBLNotice {
            get {
                return ResourceManager.GetString("MBLNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Archive content is encrypted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MCAEncryptedNotice {
            get {
                return ResourceManager.GetString("MCAEncryptedNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose title or enter a key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MCGChoose {
            get {
                return ResourceManager.GetString("MCGChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   8-bit encryption key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MCGLabelKey {
            get {
                return ResourceManager.GetString("MCGLabelKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adding file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgAddingFile {
            get {
                return ResourceManager.GetString("MsgAddingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calculating checksum... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgCalculatingChecksum {
            get {
                return ResourceManager.GetString("MsgCalculatingChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compressing index... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgCompressingIndex {
            get {
                return ResourceManager.GetString("MsgCompressingIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encryption key required for archive creation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgCreationKeyRequired {
            get {
                return ResourceManager.GetString("MsgCreationKeyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encryption method not implemented に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgEncNotImplemented {
            get {
                return ResourceManager.GetString("MsgEncNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File name extension too long. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgExtensionTooLong {
            get {
                return ResourceManager.GetString("MsgExtensionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File name is too long に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgFileNameTooLong {
            get {
                return ResourceManager.GetString("MsgFileNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File name contains illegal characters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgIllegalCharacters {
            get {
                return ResourceManager.GetString("MsgIllegalCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}: image format not recognized. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgInvalidImageFormat {
            get {
                return ResourceManager.GetString("MsgInvalidImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid archive version specified. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgInvalidVersion {
            get {
                return ResourceManager.GetString("MsgInvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File name without extension. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgNoExtension {
            get {
                return ResourceManager.GetString("MsgNoExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of files exceedes archive limit. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgTooManyFiles {
            get {
                return ResourceManager.GetString("MsgTooManyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updating index... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgUpdatingIndex {
            get {
                return ResourceManager.GetString("MsgUpdatingIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Writing index... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgWritingIndex {
            get {
                return ResourceManager.GetString("MsgWritingIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compress contents に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NPACompressContents {
            get {
                return ResourceManager.GetString("NPACompressContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nitro+ resource archive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NPADescription {
            get {
                return ResourceManager.GetString("NPADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encryption keys
        ///(required even if contents is not encrypted) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NPAKeys {
            get {
                return ResourceManager.GetString("NPAKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nitro+ Steins;Gate resource archive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NPASteinsGateDescription {
            get {
                return ResourceManager.GetString("NPASteinsGateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NScripter game engine resource archive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NSADescription {
            get {
                return ResourceManager.GetString("NSADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default audio sampling rate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ODNAudioSampleRate {
            get {
                return ResourceManager.GetString("ODNAudioSampleRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fix Ogg files checksums に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OGGFixCrc {
            get {
                return ResourceManager.GetString("OGGFixCrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Archive type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ONSArchiveType {
            get {
                return ResourceManager.GetString("ONSArchiveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compression に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ONSCompression {
            get {
                return ResourceManager.GetString("ONSCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ONSCompressionNone {
            get {
                return ResourceManager.GetString("ONSCompressionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flying Shine resource archive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PDDescription {
            get {
                return ResourceManager.GetString("PDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scramble contents に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PDScrambleContents {
            get {
                return ResourceManager.GetString("PDScrambleContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use default encryption scheme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QLIEDefaultScheme {
            get {
                return ResourceManager.GetString("QLIEDefaultScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load transparency data from RC8 bitmap に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RCTApplyMask {
            get {
                return ResourceManager.GetString("RCTApplyMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automatically combine incremental frames に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RCTOverlayFrames {
            get {
                return ResourceManager.GetString("RCTOverlayFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ren&apos;Py game engine archive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RPADescription {
            get {
                return ResourceManager.GetString("RPADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   32-bit key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RPALabelKey {
            get {
                return ResourceManager.GetString("RPALabelKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File resembles RPM resource archive,
        ///but encryption key guess failed.
        ///Choose appropriate encryption scheme. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RPMEncryptedNotice {
            get {
                return ResourceManager.GetString("RPMEncryptedNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Amaterasu Translations Muv-Luv script file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SCRDescription {
            get {
                return ResourceManager.GetString("SCRDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filename encoding に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SGLabelEncoding {
            get {
                return ResourceManager.GetString("SGLabelEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hex number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TooltipHex {
            get {
                return ResourceManager.GetString("TooltipHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maximum file name length
        ///(not including extension) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WARCLabelLength {
            get {
                return ResourceManager.GetString("WARCLabelLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Liar-soft game resource archive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string XFLDescription {
            get {
                return ResourceManager.GetString("XFLDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compress contents に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string XP3CompressContents {
            get {
                return ResourceManager.GetString("XP3CompressContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compress directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string XP3CompressHeader {
            get {
                return ResourceManager.GetString("XP3CompressHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KiriKiri game engine resource archive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string XP3Description {
            get {
                return ResourceManager.GetString("XP3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Archive content could be encrypted.
        ///Choose appropriate encryption scheme. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string XP3EncryptedNotice {
            get {
                return ResourceManager.GetString("XP3EncryptedNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string XP3LabelVersion {
            get {
                return ResourceManager.GetString("XP3LabelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retain directory structure に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string XP3RetainStructure {
            get {
                return ResourceManager.GetString("XP3RetainStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yu-Ris game engine resource archive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string YPFDescription {
            get {
                return ResourceManager.GetString("YPFDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   8-bit encryption key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string YPFLabelKey {
            get {
                return ResourceManager.GetString("YPFLabelKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Archive version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string YPFLabelVersion {
            get {
                return ResourceManager.GetString("YPFLabelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Archive directory is encrypted.
        ///Choose appropriate encryption scheme. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string YPFNotice {
            get {
                return ResourceManager.GetString("YPFNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Try to guess に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string YPFTryGuess {
            get {
                return ResourceManager.GetString("YPFTryGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Archive content is encrypted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZIPEncryptedNotice {
            get {
                return ResourceManager.GetString("ZIPEncryptedNotice", resourceCulture);
            }
        }
    }
}
