//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameRes.Strings {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class garStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal garStrings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameRes.Strings.garStrings", typeof(garStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Enables various extensions, such as transparency support. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BMPExtensionsDesc {
            get {
                return ResourceManager.GetString("BMPExtensionsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable BMP format extensions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BMPExtensionsText {
            get {
                return ResourceManager.GetString("BMPExtensionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JPEG compression quality に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JPEGQualityText {
            get {
                return ResourceManager.GetString("JPEGQualityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File is empty に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgFileIsEmpty {
            get {
                return ResourceManager.GetString("MsgFileIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File is too large に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgFileTooLarge {
            get {
                return ResourceManager.GetString("MsgFileTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inappropriate encryption scheme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgInvalidEncryption {
            get {
                return ResourceManager.GetString("MsgInvalidEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid file name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgInvalidFileName {
            get {
                return ResourceManager.GetString("MsgInvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid file format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgInvalidFormat {
            get {
                return ResourceManager.GetString("MsgInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown encryption scheme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgUnknownEncryption {
            get {
                return ResourceManager.GetString("MsgUnknownEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   file could not be opened as resource archive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgUnknownFormat {
            get {
                return ResourceManager.GetString("MsgUnknownFormat", resourceCulture);
            }
        }
    }
}
