//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARbro.GUI.Strings {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class guiStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal guiStrings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GARbro.GUI.Strings.guiStrings", typeof(guiStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   _Abort に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonAbort {
            get {
                return ResourceManager.GetString("ButtonAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonApply {
            get {
                return ResourceManager.GetString("ButtonApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Continue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonContinue {
            get {
                return ResourceManager.GetString("ButtonContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonConvert {
            get {
                return ResourceManager.GetString("ButtonConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Download に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonDownload {
            get {
                return ResourceManager.GetString("ButtonDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extract に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonExtract {
            get {
                return ResourceManager.GetString("ButtonExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Overwrite に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonOverwrite {
            get {
                return ResourceManager.GetString("ButtonOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Rename に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonRename {
            get {
                return ResourceManager.GetString("ButtonRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Skip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonSkip {
            get {
                return ResourceManager.GetString("ButtonSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CtxMenuClose {
            get {
                return ResourceManager.GetString("CtxMenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert multimedia... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CtxMenuConvert {
            get {
                return ResourceManager.GetString("CtxMenuConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CtxMenuCopy {
            get {
                return ResourceManager.GetString("CtxMenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create archive... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CtxMenuCreate {
            get {
                return ResourceManager.GetString("CtxMenuCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CtxMenuCut {
            get {
                return ResourceManager.GetString("CtxMenuCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CtxMenuDelete {
            get {
                return ResourceManager.GetString("CtxMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Browse in _Explorer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CtxMenuExplorer {
            get {
                return ResourceManager.GetString("CtxMenuExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extract に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CtxMenuExtract {
            get {
                return ResourceManager.GetString("CtxMenuExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Assign file type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CtxMenuFileType {
            get {
                return ResourceManager.GetString("CtxMenuFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CtxMenuOpen {
            get {
                return ResourceManager.GetString("CtxMenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CtxMenuPaste {
            get {
                return ResourceManager.GetString("CtxMenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CtxMenuRefresh {
            get {
                return ResourceManager.GetString("CtxMenuRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Rename に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CtxMenuRename {
            get {
                return ResourceManager.GetString("CtxMenuRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select files by mask... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CtxMenuSelectByMask {
            get {
                return ResourceManager.GetString("CtxMenuSelectByMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort by に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CtxMenuSortBy {
            get {
                return ResourceManager.GetString("CtxMenuSortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CtxMenuSortByName {
            get {
                return ResourceManager.GetString("CtxMenuSortByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CtxMenuSortBySize {
            get {
                return ResourceManager.GetString("CtxMenuSortBySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CtxMenuSortByType {
            get {
                return ResourceManager.GetString("CtxMenuSortByType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unsorted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CtxMenuUnsorted {
            get {
                return ResourceManager.GetString("CtxMenuUnsorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HeaderName {
            get {
                return ResourceManager.GetString("HeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HeaderSize {
            get {
                return ResourceManager.GetString("HeaderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HeaderType {
            get {
                return ResourceManager.GetString("HeaderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A_pply to all duplicate files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelApplyToAll {
            get {
                return ResourceManager.GetString("LabelApplyToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Archive format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelArchiveFormat {
            get {
                return ResourceManager.GetString("LabelArchiveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Archive name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelArchiveName {
            get {
                return ResourceManager.GetString("LabelArchiveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Archive options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelArchiveOptions {
            get {
                return ResourceManager.GetString("LabelArchiveOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Destination directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelDestinationDir {
            get {
                return ResourceManager.GetString("LabelDestinationDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose destination format for images に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelDestinationFormat {
            get {
                return ResourceManager.GetString("LabelDestinationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Development site に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelDevSite {
            get {
                return ResourceManager.GetString("LabelDevSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   What should be done? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelDuplicateFileQuestion {
            get {
                return ResourceManager.GetString("LabelDuplicateFileQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encoding に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelEncoding {
            get {
                return ResourceManager.GetString("LabelEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter wildcard mask に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelEnterMask {
            get {
                return ResourceManager.GetString("LabelEnterMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extract files from {0} to に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExtractAllTo {
            get {
                return ResourceManager.GetString("LabelExtractAllTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extract {0} to に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExtractFileTo {
            get {
                return ResourceManager.GetString("LabelExtractFileTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Ignore further errors に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelIgnoreErrors {
            get {
                return ResourceManager.GetString("LabelIgnoreErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Release notes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelReleaseNotes {
            get {
                return ResourceManager.GetString("LabelReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip incovertible files. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelSkipFailures {
            get {
                return ResourceManager.GetString("LabelSkipFailures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About Game Resource browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Check for updates... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuCheckUpdates {
            get {
                return ResourceManager.GetString("MenuCheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_xit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fit preview _window to image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuFitWindow {
            get {
                return ResourceManager.GetString("MenuFitWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Preferences に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuPreferences {
            get {
                return ResourceManager.GetString("MenuPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recent files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuRecent {
            get {
                return ResourceManager.GetString("MenuRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show/hide main _menu bar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuToggleMenuBar {
            get {
                return ResourceManager.GetString("MenuToggleMenuBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show/hide _status bar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuToggleStatusBar {
            get {
                return ResourceManager.GetString("MenuToggleStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show/hide _toolbar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuToggleToolBar {
            get {
                return ResourceManager.GetString("MenuToggleToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose files to extract に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgChooseFiles {
            get {
                return ResourceManager.GetString("MsgChooseFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete these files? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgConfirmDeleteFiles {
            get {
                return ResourceManager.GetString("MsgConfirmDeleteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Converting file {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgConvertingFile {
            get {
                return ResourceManager.GetString("MsgConvertingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Creating archive {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgCreatingArchive {
            get {
                return ResourceManager.GetString("MsgCreatingArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleted {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDeletedItem {
            get {
                return ResourceManager.GetString("MsgDeletedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleted {0} file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDeletedItems1 {
            get {
                return ResourceManager.GetString("MsgDeletedItems1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleted {0} files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDeletedItems2 {
            get {
                return ResourceManager.GetString("MsgDeletedItems2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   directory not found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDirectoryNotFound {
            get {
                return ResourceManager.GetString("MsgDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update download failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDownloadFailed {
            get {
                return ResourceManager.GetString("MsgDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   archive is empty に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgEmptyArchive {
            get {
                return ResourceManager.GetString("MsgEmptyArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error extracting file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgErrorExtracting {
            get {
                return ResourceManager.GetString("MsgErrorExtracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error opening file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgErrorOpening {
            get {
                return ResourceManager.GetString("MsgErrorOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extracted {0} into {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgExtractComplete {
            get {
                return ResourceManager.GetString("MsgExtractComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extracted {0} file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgExtractedFiles1 {
            get {
                return ResourceManager.GetString("MsgExtractedFiles1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extracted {0} files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgExtractedFiles2 {
            get {
                return ResourceManager.GetString("MsgExtractedFiles2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extracting files from {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgExtractingArchive {
            get {
                return ResourceManager.GetString("MsgExtractingArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extracting file from {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgExtractingFile {
            get {
                return ResourceManager.GetString("MsgExtractingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extracting files from {0} to {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgExtractingTo {
            get {
                return ResourceManager.GetString("MsgExtractingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgFiles1 {
            get {
                return ResourceManager.GetString("MsgFiles1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgFiles2 {
            get {
                return ResourceManager.GetString("MsgFiles2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image {0} x {1} x {2}bpp [{3}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgImageSize {
            get {
                return ResourceManager.GetString("MsgImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   no files to extract に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgNoFiles {
            get {
                return ResourceManager.GetString("MsgNoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No entries matching &quot;{0}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgNoMatching {
            get {
                return ResourceManager.GetString("MsgNoMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No media files selected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgNoMediaFiles {
            get {
                return ResourceManager.GetString("MsgNoMediaFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No updates currently available. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgNoUpdates {
            get {
                return ResourceManager.GetString("MsgNoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File {0}
        ///already exists.
        ///
        ///Overwrite? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgOverwrite {
            get {
                return ResourceManager.GetString("MsgOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Playing {0} / {3} / {2}bps / {1}Hz に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgPlaying {
            get {
                return ResourceManager.GetString("MsgPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgReady {
            get {
                return ResourceManager.GetString("MsgReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} file added to selection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgSelectedFiles1 {
            get {
                return ResourceManager.GetString("MsgSelectedFiles1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} files added to selection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgSelectedFiles2 {
            get {
                return ResourceManager.GetString("MsgSelectedFiles2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   unable to interpret audio format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgUnableInterpretAudio {
            get {
                return ResourceManager.GetString("MsgUnableInterpretAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   unable to interpret image format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgUnableInterpretImage {
            get {
                return ResourceManager.GetString("MsgUnableInterpretImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Formats database update available. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgUpdateAvailable {
            get {
                return ResourceManager.GetString("MsgUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Formats database updated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgUpdateComplete {
            get {
                return ResourceManager.GetString("MsgUpdateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update check failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgUpdateFailed {
            get {
                return ResourceManager.GetString("MsgUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GARbro version is up to date. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgUpToDate {
            get {
                return ResourceManager.GetString("MsgUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgVersion {
            get {
                return ResourceManager.GetString("MsgVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Archives に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextAboutArchives {
            get {
                return ResourceManager.GetString("TextAboutArchives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Audio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextAboutAudio {
            get {
                return ResourceManager.GetString("TextAboutAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [builtin] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextAboutBuiltin {
            get {
                return ResourceManager.GetString("TextAboutBuiltin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Images に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextAboutImages {
            get {
                return ResourceManager.GetString("TextAboutImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   License に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextAboutLicense {
            get {
                return ResourceManager.GetString("TextAboutLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About Game Resource browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextAboutTitle {
            get {
                return ResourceManager.GetString("TextAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextAllFiles {
            get {
                return ResourceManager.GetString("TextAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   as is に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextAsIs {
            get {
                return ResourceManager.GetString("TextAsIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Audio will be converted to either WAV, MP3 or OGG. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextAudioConversion {
            get {
                return ResourceManager.GetString("TextAudioConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose archive location に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextChooseArchive {
            get {
                return ResourceManager.GetString("TextChooseArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose destination directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextChooseDestDir {
            get {
                return ResourceManager.GetString("TextChooseDestDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm overwrite に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextConfirmOverwrite {
            get {
                return ResourceManager.GetString("TextConfirmOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert audio to common format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextConvertAudio {
            get {
                return ResourceManager.GetString("TextConvertAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Media conversion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextConvertMedia {
            get {
                return ResourceManager.GetString("TextConvertMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create archive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextCreateArchive {
            get {
                return ResourceManager.GetString("TextCreateArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Archive creation error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextCreateArchiveError {
            get {
                return ResourceManager.GetString("TextCreateArchiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextDeleteFiles {
            get {
                return ResourceManager.GetString("TextDeleteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text encoding に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextEncoding {
            get {
                return ResourceManager.GetString("TextEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error occured while converting file
        ///{0}
        ///{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextErrorConverting {
            get {
                return ResourceManager.GetString("TextErrorConverting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error occured while extracting file
        ///{0}
        ///{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextErrorExtracting {
            get {
                return ResourceManager.GetString("TextErrorExtracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extract audio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextExtractAudio {
            get {
                return ResourceManager.GetString("TextExtractAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extract images に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextExtractImages {
            get {
                return ResourceManager.GetString("TextExtractImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File extraction error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextExtractionError {
            get {
                return ResourceManager.GetString("TextExtractionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extract text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextExtractText {
            get {
                return ResourceManager.GetString("TextExtractText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extract from archive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextExtractTitle {
            get {
                return ResourceManager.GetString("TextExtractTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File {0} already exists in the destination folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextFileAlreadyExists {
            get {
                return ResourceManager.GetString("TextFileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Formats に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextFormats {
            get {
                return ResourceManager.GetString("TextFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multimedia conversion error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextMediaConvertError {
            get {
                return ResourceManager.GetString("TextMediaConvertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New version available: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextNewVersion {
            get {
                return ResourceManager.GetString("TextNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Archive parameters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextParametersTitle {
            get {
                return ResourceManager.GetString("TextParametersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preferences に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextPreferences {
            get {
                return ResourceManager.GetString("TextPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save as に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextSaveAs {
            get {
                return ResourceManager.GetString("TextSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save images as に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextSaveImagesAs {
            get {
                return ResourceManager.GetString("TextSaveImagesAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextSelectFiles {
            get {
                return ResourceManager.GetString("TextSelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game Resource browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextTitle {
            get {
                return ResourceManager.GetString("TextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextUpdateTitle {
            get {
                return ResourceManager.GetString("TextUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image viewer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextViewer {
            get {
                return ResourceManager.GetString("TextViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visit download page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextVisitPage {
            get {
                return ResourceManager.GetString("TextVisitPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Either WAV, MP3 or OGG に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TooltipAudioFormats {
            get {
                return ResourceManager.GetString("TooltipAudioFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TooltipBack {
            get {
                return ResourceManager.GetString("TooltipBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Forward に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TooltipForward {
            get {
                return ResourceManager.GetString("TooltipForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;DIR&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Type_directory {
            get {
                return ResourceManager.GetString("Type_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   none に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Type_NONE {
            get {
                return ResourceManager.GetString("Type_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scale large images to fit window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string winDownScaleImage {
            get {
                return ResourceManager.GetString("winDownScaleImage", resourceCulture);
            }
        }
    }
}
